[pytest]
addopts = --browser chromium
markers =
    smoke: critical tests that must pass
    regression: full regression suite
    login: tests related to login functionality
    secure_area: tests related to secure area page