
CSS_SIGN_IN_BUTTON = "button.btn-outline-white"
CSS_GUEST_LOGIN_BUTTON = "button.header-link.-guest"
CSS_HOME_LINK = "a.header-link.-active"
CSS_HEADER_LOGO = "a.header_logo"
CSS_HERO_TITLE = "h1.hero-descriptor_title"
CSS_HERO_SIGNUP_BUTTON = "button.hero-descriptor_btn"
CSS_HERO_DESCRIPTION = "p.hero-descriptor_descr"
CSS_HERO_VIDEO = "iframe.hero-video_frame"
CSS_ABOUT_TITLES = "p.about-block_title"
CSS_ABOUT_DESCR = "p.about-block_descr"
CSS_ABOUT_SECTION = "#aboutSection"
CSS_CONTACTS_SECTION = "#contactsSection"
CSS_ITHILLEL_LINK = "a[href='https://ithillel.ua']"
CSS_EMAIL_LINK = "a[href='mailto:developer@ithillel.ua']"
CSS_FACEBOOK_LINK = "a[href='https://www.facebook.com/Hillel.IT.School']"
CSS_NAV_BUTTONS = "nav.header_nav button"
CSS_SOCIAL_LINKS = "div.socials a.socials_link"
CSS_ABOUT_IMAGES = ".about-block .about-picture img"
CSS_CONTACTS_H2 = "#contactsSection h2"
CSS_FOOTER_LOGO = "footer a.footer_logo"
CSS_FOOTER_COPYRIGHT = "footer .footer_item.-left p:first-child"
CSS_FACEBOOK_ICON = "div.socials span.icon-facebook"
CSS_TELEGRAM_ICON = "div.socials span.icon-telegram"
CSS_YOUTUBE_ICON = "div.socials span.icon-youtube"
CSS_HERO_SECTION_BUTTON = "section.hero button.btn-primary"
