
SIGN_IN_BUTTON = "//button[text()='Sign In']"
SIGN_UP_BUTTON = "//button[text()='Sign up']"
ABOUT_BUTTON = "//button[text()='About']"
CONTACTS_BUTTON = "//button[text()='Contacts']"
GUEST_LOGIN_BUTTON = "//button[text()='Guest log in']"
HOME_LINK = "//a[text()='Home']"
HERO_TITLE = "//h1[text()='Do more!']"
LOG_FUEL_TITLE = "//p[text()='Log fuel expenses']"
INSTRUCTIONS_TITLE = "//p[text()='Instructions and manuals']"
CONTACTS_TITLE = "//h2[text()='Contacts']"
HEADER_LOGO = "//a[@class='header_logo']"
ABOUT_SECTION = "//*[@id='aboutSection']"
CONTACTS_SECTION = "//*[@id='contactsSection']"
FACEBOOK_LINK = "//a[@href='https://www.facebook.com/Hillel.IT.School']"
TELEGRAM_LINK = "//a[@href='https://t.me/ithillel_kyiv']"
ITHILLEL_LINK = "//a[@href='https://ithillel.ua']"
FOOTER_EMAIL = "//a[@href='mailto:developer@ithillel.ua']"
NAV_ABOUT_BUTTON = "//header//nav//button[text()='About']"
NAV_CONTACTS_BUTTON = "//header//nav//button[text()='Contacts']"
HEADER_RIGHT_SIGNIN = "//div[contains(@class,'header_right')]//button[text()='Sign In']"
HERO_SECTION_SIGNUP = "//section[contains(@class,'hero')]//button[text()='Sign up']"
FOOTER_EMAIL_LINK = "//footer//a[@href='mailto:developer@ithillel.ua']"
FOOTER_COPYRIGHT = "//footer//p[contains(text(),'2021 Hillel')]"
ABOUT_BLOCK_IMAGE = "//div[@class='about-block']//img[@alt='Instructions']"
CONTACTS_SOCIAL_LINKS = "//div[@class='contacts_socials socials']//a[@rel='nofollow']"
